### PR TITLE
Update other-websites.csv

### PR DESCRIPTION
**Pull request by cfx47**
Located multiple DOT/FAA domains through routine task. Requesting they be added to DOT scope.

angmyaccess.faa.gov
origin-ksnoos.faa.gov
origin-angmyaccess.faa.gov
ksnmyaccess.faa.gov
origin-mysite.ksn2.faa.gov
origin-vps.faa.gov
origin-ksn2test.faa.gov
angprepmyaccess.faa.gov
angdevmyaccess.faa.gov
ksnsp2019portal.faa.gov
ang-a-test-old.faa.gov
origin-ang-a-dev.faa.gov
origin-ksn2testoos.faa.gov
origin-ang-a-test.faa.gov
ksn2test-old.faa.gov
origin-avssp.faa.gov
origin-ang-a.faa.gov
ksn2testoos-old.faa.gov
angtestmyaccess.faa.gov
origin-ksn2.faa.gov
origin-ang-a-prep.faa.gov

### CODE REVIEW

**Review by jsf9k — CHANGES_REQUESTED** [review]
The new domains need to be sorted alphabetically into the rest of the file.

@mcdonnnj - What tool did you use to do this before?  `sort` doesn't produce the same results as whatever you used.

**Comment by h-m-f-t** [comment]
For my purposes, I don't care much about this file being in alphabetical order, presuming that if order is important for others they would sort it on their side. What do you think, @jsf9k?

**Comment by mcdonnnj** [comment]
> For my purposes, I don't care much about this file being in alphabetical order, presuming that if order is important for others they would sort it on their side. What do you think, @jsf9k?

@h-m-f-t Sorting them alphabetically is more around human data management. It is trivial to see at a glance if there is duplication during review if hosts are sorted.

**Comment by h-m-f-t** [comment]
Cool. @cfx47 if you'd sort this file in one commit, and then add the new data in another sorted commit, I'll merge this.

**Comment by mcdonnnj** [comment]
@h-m-f-t @jsf9k Just to expedite this pull request I have sorted the file in https://github.com/cisagov/dotgov-data/pull/137/commits/d965d7e68e944badb2dd6f00eeaa34ed34a3394f.

**Comment by mcdonnnj** [comment]
> The new domains need to be sorted alphabetically into the rest of the file.
> 
> @mcdonnnj - What tool did you use to do this before? `sort` doesn't produce the same results as whatever you used.

@jsf9k Just to respond to this I use the command available in VSCodium. GNU `sort` approaches sorting in the dumbest (most basic) way possible (ASCII order). This does not align with guidelines for alphabetical sorting like [NISO Technical Report 3](https://www.niso.org/sites/default/files/2017-08/tr03.pdf).

**Review by jsf9k — APPROVED** [review]

**Review by mcdonnnj — APPROVED** [review]

**Comment by h-m-f-t** [comment]
Thanks, team.

**Pull request merged**
